HOST: https://www.positivespace.io/api/


--- Positive Space API v1 ---
---
# Welcome to the Positive Space API v1 documentation.

This is a working document. Please leave comments.
---


--
Users
The following is a section of resources related to users.
--

List users
GET /users{?login,email,username,id,following,followers,accepting_conversations_with,publishable,complete,endorsed,unendorsed,visible,order,page,per}
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Spaces
The following is a section of resources related to spaces.
--

List spaces
GET /spaces
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Conversations
The following is a section of resources related to conversations.
--

List conversations
GET /users/{user_id}/conversations
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Messages
The following is a section of resources related to messages.
--

List messages
GET /users/{user_id}/messages
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Reviews
The following is a section of resources related to reviews.
--

List reviews
GET /conversations/{conversation_id}/reviews
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Tags
The following is a section of resources related to tags.
--

List tags
GET /tags
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Images
The following is a section of resources related to images.
--

List images
GET /images
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }