HOST: http://www.positivespace.io/api/


--- +_ ---

---
### Welcome to the Positive Space API V1 documentation.
---


--
Users
The following is a section of resources related to users
--

List users
GET /users
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Spaces
The following is a section of resources related to spaces
--

List spaces
GET /spaces
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Conversations
The following is a section of resources related to spaces
--

List conversations
GET /conversations
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }


--
Messages
The following is a section of resources related to spaces
--

List messages
GET /messages
< 200
< Content-Type: application/json
{ "collection": [
{ "id": 1 }
] }